/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchConfigSchemaSearchable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchConfigSchemaSearchable{}

// SearchConfigSchemaSearchable contains the configurations needed to define which index attributes can be used for search
type SearchConfigSchemaSearchable struct {
	// json array of attributes of index which can be used for search
	Attribute            string `json:"attribute"`
	AdditionalProperties map[string]interface{}
}

type _SearchConfigSchemaSearchable SearchConfigSchemaSearchable

// NewSearchConfigSchemaSearchable instantiates a new SearchConfigSchemaSearchable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchConfigSchemaSearchable(attribute string) *SearchConfigSchemaSearchable {
	this := SearchConfigSchemaSearchable{}
	this.Attribute = attribute
	return &this
}

// NewSearchConfigSchemaSearchableWithDefaults instantiates a new SearchConfigSchemaSearchable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchConfigSchemaSearchableWithDefaults() *SearchConfigSchemaSearchable {
	this := SearchConfigSchemaSearchable{}
	return &this
}

// GetAttribute returns the Attribute field value
func (o *SearchConfigSchemaSearchable) GetAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value
// and a boolean to check if the value has been set.
func (o *SearchConfigSchemaSearchable) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribute, true
}

// SetAttribute sets field value
func (o *SearchConfigSchemaSearchable) SetAttribute(v string) {
	o.Attribute = v
}

func (o SearchConfigSchemaSearchable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchConfigSchemaSearchable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attribute"] = o.Attribute

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchConfigSchemaSearchable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchConfigSchemaSearchable := _SearchConfigSchemaSearchable{}

	err = json.Unmarshal(data, &varSearchConfigSchemaSearchable)

	if err != nil {
		return err
	}

	*o = SearchConfigSchemaSearchable(varSearchConfigSchemaSearchable)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchConfigSchemaSearchable) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchConfigSchemaSearchable) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchConfigSchemaSearchable struct {
	value *SearchConfigSchemaSearchable
	isSet bool
}

func (v NullableSearchConfigSchemaSearchable) Get() *SearchConfigSchemaSearchable {
	return v.value
}

func (v *NullableSearchConfigSchemaSearchable) Set(val *SearchConfigSchemaSearchable) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchConfigSchemaSearchable) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchConfigSchemaSearchable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchConfigSchemaSearchable(val *SearchConfigSchemaSearchable) *NullableSearchConfigSchemaSearchable {
	return &NullableSearchConfigSchemaSearchable{value: val, isSet: true}
}

func (v NullableSearchConfigSchemaSearchable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchConfigSchemaSearchable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
