/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
)

// checks if the SearchDeleteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchDeleteResponse{}

// SearchDeleteResponse struct for SearchDeleteResponse
type SearchDeleteResponse struct {
	Errors               []SearchDeleteError `json:"errors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchDeleteResponse SearchDeleteResponse

// NewSearchDeleteResponse instantiates a new SearchDeleteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchDeleteResponse() *SearchDeleteResponse {
	this := SearchDeleteResponse{}
	return &this
}

// NewSearchDeleteResponseWithDefaults instantiates a new SearchDeleteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchDeleteResponseWithDefaults() *SearchDeleteResponse {
	this := SearchDeleteResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SearchDeleteResponse) GetErrors() []SearchDeleteError {
	if o == nil || IsNil(o.Errors) {
		var ret []SearchDeleteError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchDeleteResponse) GetErrorsOk() ([]SearchDeleteError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SearchDeleteResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []SearchDeleteError and assigns it to the Errors field.
func (o *SearchDeleteResponse) SetErrors(v []SearchDeleteError) {
	o.Errors = v
}

func (o SearchDeleteResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchDeleteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchDeleteResponse) UnmarshalJSON(data []byte) (err error) {
	varSearchDeleteResponse := _SearchDeleteResponse{}

	err = json.Unmarshal(data, &varSearchDeleteResponse)

	if err != nil {
		return err
	}

	*o = SearchDeleteResponse(varSearchDeleteResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchDeleteResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchDeleteResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchDeleteResponse struct {
	value *SearchDeleteResponse
	isSet bool
}

func (v NullableSearchDeleteResponse) Get() *SearchDeleteResponse {
	return v.value
}

func (v *NullableSearchDeleteResponse) Set(val *SearchDeleteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchDeleteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchDeleteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchDeleteResponse(val *SearchDeleteResponse) *NullableSearchDeleteResponse {
	return &NullableSearchDeleteResponse{value: val, isSet: true}
}

func (v NullableSearchDeleteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchDeleteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
