/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchParamSort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchParamSort{}

// SearchParamSort contains a list of document attributes on which order the result for
type SearchParamSort struct {
	// JSON string that contains the list of attributes you want search results to be ordered by
	Attribute            string          `json:"attribute"`
	Order                *ParamSortOrder `json:"order,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchParamSort SearchParamSort

// NewSearchParamSort instantiates a new SearchParamSort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchParamSort(attribute string) *SearchParamSort {
	this := SearchParamSort{}
	this.Attribute = attribute
	var order ParamSortOrder = PARAMSORTORDER_ASC
	this.Order = &order
	return &this
}

// NewSearchParamSortWithDefaults instantiates a new SearchParamSort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchParamSortWithDefaults() *SearchParamSort {
	this := SearchParamSort{}
	var order ParamSortOrder = PARAMSORTORDER_ASC
	this.Order = &order
	return &this
}

// GetAttribute returns the Attribute field value
func (o *SearchParamSort) GetAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value
// and a boolean to check if the value has been set.
func (o *SearchParamSort) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribute, true
}

// SetAttribute sets field value
func (o *SearchParamSort) SetAttribute(v string) {
	o.Attribute = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *SearchParamSort) GetOrder() ParamSortOrder {
	if o == nil || IsNil(o.Order) {
		var ret ParamSortOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParamSort) GetOrderOk() (*ParamSortOrder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *SearchParamSort) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given ParamSortOrder and assigns it to the Order field.
func (o *SearchParamSort) SetOrder(v ParamSortOrder) {
	o.Order = &v
}

func (o SearchParamSort) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchParamSort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attribute"] = o.Attribute
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchParamSort) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchParamSort := _SearchParamSort{}

	err = json.Unmarshal(data, &varSearchParamSort)

	if err != nil {
		return err
	}

	*o = SearchParamSort(varSearchParamSort)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute")
		delete(additionalProperties, "order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchParamSort) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchParamSort) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchParamSort struct {
	value *SearchParamSort
	isSet bool
}

func (v NullableSearchParamSort) Get() *SearchParamSort {
	return v.value
}

func (v *NullableSearchParamSort) Set(val *SearchParamSort) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchParamSort) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchParamSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchParamSort(val *SearchParamSort) *NullableSearchParamSort {
	return &NullableSearchParamSort{value: val, isSet: true}
}

func (v NullableSearchParamSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchParamSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
