/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchWriteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchWriteResponse{}

// SearchWriteResponse contains write operation result response from search service
type SearchWriteResponse struct {
	// elasticsearch index where the write request was processed
	Index string `json:"index"`
	// array of errors obtained during elasticsearch documents write or update
	Errors               []SearchWriteError `json:"errors,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SearchWriteResponse SearchWriteResponse

// NewSearchWriteResponse instantiates a new SearchWriteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchWriteResponse(index string) *SearchWriteResponse {
	this := SearchWriteResponse{}
	this.Index = index
	return &this
}

// NewSearchWriteResponseWithDefaults instantiates a new SearchWriteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchWriteResponseWithDefaults() *SearchWriteResponse {
	this := SearchWriteResponse{}
	return &this
}

// GetIndex returns the Index field value
func (o *SearchWriteResponse) GetIndex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *SearchWriteResponse) GetIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *SearchWriteResponse) SetIndex(v string) {
	o.Index = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SearchWriteResponse) GetErrors() []SearchWriteError {
	if o == nil || IsNil(o.Errors) {
		var ret []SearchWriteError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchWriteResponse) GetErrorsOk() ([]SearchWriteError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SearchWriteResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []SearchWriteError and assigns it to the Errors field.
func (o *SearchWriteResponse) SetErrors(v []SearchWriteError) {
	o.Errors = v
}

func (o SearchWriteResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchWriteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchWriteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchWriteResponse := _SearchWriteResponse{}

	err = json.Unmarshal(data, &varSearchWriteResponse)

	if err != nil {
		return err
	}

	*o = SearchWriteResponse(varSearchWriteResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "index")
		delete(additionalProperties, "errors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchWriteResponse) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchWriteResponse) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchWriteResponse struct {
	value *SearchWriteResponse
	isSet bool
}

func (v NullableSearchWriteResponse) Get() *SearchWriteResponse {
	return v.value
}

func (v *NullableSearchWriteResponse) Set(val *SearchWriteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchWriteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchWriteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchWriteResponse(val *SearchWriteResponse) *NullableSearchWriteResponse {
	return &NullableSearchWriteResponse{value: val, isSet: true}
}

func (v NullableSearchWriteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchWriteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
