/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchPayload{}

// SearchPayload contains the search request payload
type SearchPayload struct {
	// index where to search data
	Index                string       `json:"index"`
	Params               SearchParams `json:"params"`
	AdditionalProperties map[string]interface{}
}

type _SearchPayload SearchPayload

// NewSearchPayload instantiates a new SearchPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchPayload(index string, params SearchParams) *SearchPayload {
	this := SearchPayload{}
	this.Index = index
	this.Params = params
	return &this
}

// NewSearchPayloadWithDefaults instantiates a new SearchPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchPayloadWithDefaults() *SearchPayload {
	this := SearchPayload{}
	return &this
}

// GetIndex returns the Index field value
func (o *SearchPayload) GetIndex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *SearchPayload) GetIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *SearchPayload) SetIndex(v string) {
	o.Index = v
}

// GetParams returns the Params field value
func (o *SearchPayload) GetParams() SearchParams {
	if o == nil {
		var ret SearchParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *SearchPayload) GetParamsOk() (*SearchParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *SearchPayload) SetParams(v SearchParams) {
	o.Params = v
}

func (o SearchPayload) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	toSerialize["params"] = o.Params

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchPayload := _SearchPayload{}

	err = json.Unmarshal(data, &varSearchPayload)

	if err != nil {
		return err
	}

	*o = SearchPayload(varSearchPayload)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "index")
		delete(additionalProperties, "params")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchPayload) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchPayload) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchPayload struct {
	value *SearchPayload
	isSet bool
}

func (v NullableSearchPayload) Get() *SearchPayload {
	return v.value
}

func (v *NullableSearchPayload) Set(val *SearchPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchPayload(val *SearchPayload) *NullableSearchPayload {
	return &NullableSearchPayload{value: val, isSet: true}
}

func (v NullableSearchPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
