/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchQueryError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchQueryError{}

// SearchQueryError contains error information obtained during search process
type SearchQueryError struct {
	// query error code obtained during elastic search query request
	Code string `json:"code"`
	// query error message obtained during elastic search query request
	Message              string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _SearchQueryError SearchQueryError

// NewSearchQueryError instantiates a new SearchQueryError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchQueryError(code string, message string) *SearchQueryError {
	this := SearchQueryError{}
	this.Code = code
	this.Message = message
	return &this
}

// NewSearchQueryErrorWithDefaults instantiates a new SearchQueryError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchQueryErrorWithDefaults() *SearchQueryError {
	this := SearchQueryError{}
	return &this
}

// GetCode returns the Code field value
func (o *SearchQueryError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *SearchQueryError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *SearchQueryError) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *SearchQueryError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SearchQueryError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SearchQueryError) SetMessage(v string) {
	o.Message = v
}

func (o SearchQueryError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchQueryError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchQueryError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchQueryError := _SearchQueryError{}

	err = json.Unmarshal(data, &varSearchQueryError)

	if err != nil {
		return err
	}

	*o = SearchQueryError(varSearchQueryError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchQueryError) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchQueryError) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchQueryError struct {
	value *SearchQueryError
	isSet bool
}

func (v NullableSearchQueryError) Get() *SearchQueryError {
	return v.value
}

func (v *NullableSearchQueryError) Set(val *SearchQueryError) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchQueryError) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchQueryError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchQueryError(val *SearchQueryError) *NullableSearchQueryError {
	return &NullableSearchQueryError{value: val, isSet: true}
}

func (v NullableSearchQueryError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchQueryError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
