/*
Search Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package search

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchParamSearchable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchParamSearchable{}

// SearchParamSearchable contains a list of attributes where the search term to be searched
type SearchParamSearchable struct {
	// JSON string that contains the list of attributes where to search the indicated term
	Attribute            string `json:"attribute"`
	AdditionalProperties map[string]interface{}
}

type _SearchParamSearchable SearchParamSearchable

// NewSearchParamSearchable instantiates a new SearchParamSearchable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchParamSearchable(attribute string) *SearchParamSearchable {
	this := SearchParamSearchable{}
	this.Attribute = attribute
	return &this
}

// NewSearchParamSearchableWithDefaults instantiates a new SearchParamSearchable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchParamSearchableWithDefaults() *SearchParamSearchable {
	this := SearchParamSearchable{}
	return &this
}

// GetAttribute returns the Attribute field value
func (o *SearchParamSearchable) GetAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value
// and a boolean to check if the value has been set.
func (o *SearchParamSearchable) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribute, true
}

// SetAttribute sets field value
func (o *SearchParamSearchable) SetAttribute(v string) {
	o.Attribute = v
}

func (o SearchParamSearchable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchParamSearchable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attribute"] = o.Attribute

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchParamSearchable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchParamSearchable := _SearchParamSearchable{}

	err = json.Unmarshal(data, &varSearchParamSearchable)

	if err != nil {
		return err
	}

	*o = SearchParamSearchable(varSearchParamSearchable)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *SearchParamSearchable) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *SearchParamSearchable) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableSearchParamSearchable struct {
	value *SearchParamSearchable
	isSet bool
}

func (v NullableSearchParamSearchable) Get() *SearchParamSearchable {
	return v.value
}

func (v *NullableSearchParamSearchable) Set(val *SearchParamSearchable) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchParamSearchable) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchParamSearchable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchParamSearchable(val *SearchParamSearchable) *NullableSearchParamSearchable {
	return &NullableSearchParamSearchable{value: val, isSet: true}
}

func (v NullableSearchParamSearchable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchParamSearchable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
